const companies = [
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0BFF00",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#291713",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0F1ED3",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#DE00F8",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#00E9F8",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#000000",
    textColor: "white",
  },

  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0BFF01",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#291719",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0F1ED9",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#DE00F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#00E9F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#553556",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0BFF01",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#291719",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0F1ED9",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#DE00F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#00E9F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#553556",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0BFF01",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#291719",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0F1ED9",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#DE00F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#00E9F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#553556",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0BFF01",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#291719",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0F1ED9",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#DE00F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#00E9F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#553556",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0BFF01",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#291719",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#0F1ED9",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#DE00F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#00E9F1",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    backgroundColor: "#553556",
    textColor: "white",
  },
];
export default companies;
